hosts: []

auth:
  session:
    cookie_max_age_seconds: 28800
    max_lifetime_seconds: 28800
    idle_timeout_seconds: 1800
  ldap:
    enabled: true
    url: "ldap://ldap:389"
    base_dn: "ou=people,dc=example,dc=org"
    method: "simple"
    user_template: "uid=%s,%s"
    bind_dn: "cn=admin,dc=example,dc=org"
    bind_pw: "admin"
    insecure_ldap: true
    required_groups: ["cerebro-admins"]
    group_search:
      base_dn: "ou=groups,dc=example,dc=org"
      user_attr: "member"
      user_attr_template: "uid=%s,ou=people,dc=example,dc=org"
      group: "(objectClass=groupOfNames)"
      name_attr: "cn"

server:
  port: 9000
  base_path: "/"
  secret: "${APPLICATION_SECRET}"
  cookie_secure: false
  csrf_enabled: true

es:
  allow_ad_hoc_hosts: false
