// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Alias = {
    /**
     * Alias name.
     */
    alias: string;
    /**
     * Optional alias filter query (null when absent).
     */
    filter: unknown;
    /**
     * Index the alias points at.
     */
    index: string;
    /**
     * Optional index routing value (null when absent).
     */
    index_routing: unknown;
    /**
     * Optional search routing value (null when absent).
     */
    search_routing: unknown;
};

export type AliasesUpdateInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Alias actions in Elasticsearch _aliases format, e.g. {"add": {...}} / {"remove": {...}}.
     */
    changes?: Array<unknown> | null;
};

export type AnalysisAnalyzerInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Analyzer name.
     */
    analyzer: string;
    /**
     * Text to analyze.
     */
    text: string;
};

export type AnalysisFieldInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Field name.
     */
    field: string;
    /**
     * Text to analyze.
     */
    text: string;
};

export type Changes = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Cluster name.
     */
    cluster_name: unknown;
    /**
     * All index names, including closed indices.
     */
    indices: Array<string> | null;
    /**
     * Distinct node names.
     */
    nodes: Array<unknown> | null;
};

export type DataExplorerResult = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Columns discovered from the current result page.
     */
    columns: Array<string> | null;
    /**
     * Flattened documents for tabular display.
     */
    rows: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Total matching documents reported by Elasticsearch.
     */
    total: number;
};

export type DataExplorerSaveInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Document _source JSON object.
     */
    document: unknown;
    /**
     * Optional document id. Empty creates a new document id.
     */
    id?: string;
};

export type DataExplorerSearchInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Zero-based page number.
     */
    page?: number;
    /**
     * Optional simple query string.
     */
    query?: string;
    /**
     * Query language mode. KQL is the Kibana-like default; Lucene maps to Elasticsearch query_string syntax.
     */
    query_mode?: 'kql' | 'lucene';
    /**
     * Rows per page.
     */
    size?: number;
    /**
     * Optional field to sort by.
     */
    sort_field?: string;
    /**
     * Sort direction.
     */
    sort_order?: 'asc' | 'desc';
};

export type DataStream = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    backing_indices: Array<DataStreamBackingIndex> | null;
    backing_indices_count: number;
    generation: number;
    hidden: boolean;
    lifecycle?: unknown;
    managed_by?: string;
    maximum_timestamp?: unknown;
    name: string;
    next_generation_managed_by?: string;
    prefer_ilm: boolean;
    rollover_on_write: boolean;
    status?: string;
    store_size_bytes: number;
    system: boolean;
    template?: string;
    timestamp_field?: string;
};

export type DataStreamAttachIlmInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * ILM policy name.
     */
    policy: string;
    /**
     * Whether to rollover the data stream after updating the template.
     */
    rollover: boolean;
    /**
     * Whether existing backing indices should get index.lifecycle.name.
     */
    update_backing_indices: boolean;
};

export type DataStreamAttachIlmResult = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    backing_indices_updated: boolean;
    data_stream: string;
    policy: string;
    rolled_over: boolean;
    template: string;
    template_updated: boolean;
};

export type DataStreamBackingIndex = {
    docs_count?: unknown;
    health?: string;
    ilm_action?: string;
    ilm_error?: string;
    ilm_managed: boolean;
    ilm_phase?: string;
    ilm_policy?: string;
    ilm_step?: string;
    managed_by?: string;
    name: string;
    status?: string;
    store_size_bytes?: unknown;
    uuid?: string;
    write_index: boolean;
};

export type DataStreamDetachIlmResult = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    backing_indices_updated: boolean;
    data_stream: string;
    template: string;
    template_updated: boolean;
};

export type DataStreamLifecycleInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Data stream lifecycle body.
     */
    lifecycle: unknown;
};

export type DataStreamsResult = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Data streams.
     */
    items: Array<DataStream> | null;
    /**
     * Whether the target Elasticsearch supports data streams.
     */
    supported: boolean;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HostBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
};

export type HostRef = {
    name: string;
    slug: string;
};

export type IlmPolicy = {
    in_use_by: IlmPolicyInUseBy;
    modified_date?: unknown;
    name: string;
    phases: Array<string> | null;
    policy: unknown;
    version?: unknown;
};

export type IlmPolicyInUseBy = {
    composable_templates: Array<string> | null;
    data_streams: Array<string> | null;
    indices: Array<string> | null;
};

export type IlmPolicySaveInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * ILM policy body.
     */
    policy: unknown;
};

export type ListAlias = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Collection items.
     */
    items: Array<Alias> | null;
};

export type ListHostRef = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Collection items.
     */
    items: Array<HostRef> | null;
};

export type ListIlmPolicy = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Collection items.
     */
    items: Array<IlmPolicy> | null;
};

export type ListNode = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Collection items.
     */
    items: Array<Node> | null;
};

export type ListRepository = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Collection items.
     */
    items: Array<Repository> | null;
};

export type ListString = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Collection items.
     */
    items: Array<string> | null;
};

export type ListTemplateSummary = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Collection items.
     */
    items: Array<TemplateSummary> | null;
};

export type Metadata = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Index mappings (null when not found).
     */
    mappings: unknown;
    /**
     * Index settings (null when not found).
     */
    settings: unknown;
};

export type Node = {
    /**
     * Custom node attributes (internal ES attributes filtered out).
     */
    attributes: {
        [key: string]: unknown;
    };
    /**
     * Whether the node is a coordinating-only node.
     */
    coordinating: boolean;
    cpu: NodeCpu;
    /**
     * Whether this node is the elected master.
     */
    current_master: boolean;
    /**
     * Whether the node has a data role.
     */
    data: boolean;
    /**
     * Disk usage (null when filesystem stats are unavailable).
     */
    disk: NodeDisk;
    heap: NodeHeap;
    /**
     * Node host.
     */
    host: unknown;
    /**
     * Node id.
     */
    id: string;
    /**
     * Whether the node has the ingest role.
     */
    ingest: boolean;
    /**
     * JVM version.
     */
    jvm: unknown;
    /**
     * Whether the node is master-eligible.
     */
    master: boolean;
    /**
     * Node name.
     */
    name: unknown;
    /**
     * JVM uptime in milliseconds.
     */
    uptime: unknown;
    /**
     * Elasticsearch version.
     */
    version: unknown;
};

export type NodeCpu = {
    /**
     * 1-minute load average.
     */
    load: unknown;
    /**
     * OS CPU usage percentage.
     */
    os: unknown;
    /**
     * Process CPU usage percentage.
     */
    process: unknown;
};

export type NodeDisk = {
    /**
     * Available filesystem size in bytes.
     */
    available: number;
    /**
     * Used disk percentage.
     */
    percent: number;
    /**
     * Total filesystem size in bytes.
     */
    total: number;
};

export type NodeHeap = {
    /**
     * Maximum JVM heap.
     */
    max: unknown;
    /**
     * Used JVM heap percentage.
     */
    percent: unknown;
    /**
     * Used JVM heap.
     */
    used: unknown;
};

export type Overview = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    active_primary_shards: unknown;
    active_shards: unknown;
    closed_indices: number;
    /**
     * Cluster name.
     */
    cluster_name: unknown;
    /**
     * Total primary docs count.
     */
    docs_count: unknown;
    indices: Array<OverviewIndex> | null;
    initializing_shards: unknown;
    nodes: Array<OverviewNode> | null;
    /**
     * Number of nodes in the cluster.
     */
    number_of_nodes: unknown;
    relocating_shards: unknown;
    /**
     * Whether shard allocation is enabled (cluster.routing.allocation.enable == all).
     */
    shard_allocation: boolean;
    /**
     * Total store size in bytes.
     */
    size_in_bytes: unknown;
    /**
     * Number of dot-prefixed (system) indices.
     */
    special_indices: number;
    /**
     * Cluster health status (green/yellow/red).
     */
    status: unknown;
    total_indices: number;
    unassigned_shards: unknown;
};

export type OverviewDisk = {
    /**
     * Free filesystem size in bytes.
     */
    free: number;
    /**
     * Total filesystem size in bytes.
     */
    total: number;
    used_percent: number;
};

export type OverviewHeap = {
    /**
     * Committed JVM heap in bytes.
     */
    committed: unknown;
    /**
     * Maximum JVM heap in bytes.
     */
    max: unknown;
    /**
     * Used JVM heap in bytes.
     */
    used: unknown;
    used_percent: unknown;
};

export type OverviewIndex = {
    aliases: Array<string> | null;
    closed: boolean;
    /**
     * Data stream name when this index is a backing index.
     */
    data_stream?: string;
    deleted_docs: unknown;
    doc_count: unknown;
    /**
     * Index name.
     */
    name: string;
    num_replicas: number;
    num_shards: number;
    /**
     * Routing table shards grouped by node name ('unassigned' for unassigned shards).
     */
    shards: {
        [key: string]: Array<{
            [key: string]: unknown;
        }> | null;
    };
    /**
     * Primary store size in bytes.
     */
    size_in_bytes: unknown;
    /**
     * Whether the index is dot-prefixed (system index).
     */
    special: boolean;
    total_size_in_bytes: unknown;
    /**
     * Whether any shard is not STARTED.
     */
    unhealthy: boolean;
};

export type OverviewNode = {
    /**
     * Custom node attributes (internal ES attributes filtered out).
     */
    attributes: {
        [key: string]: unknown;
    };
    available_processors: unknown;
    /**
     * Whether the node is a coordinating-only node.
     */
    coordinating: boolean;
    cpu_percent: unknown;
    /**
     * Whether this node is the elected master.
     */
    current_master: boolean;
    /**
     * Whether the node has a data role.
     */
    data: boolean;
    disk: OverviewDisk;
    /**
     * Elasticsearch version.
     */
    es_version: unknown;
    heap: OverviewHeap;
    host: unknown;
    /**
     * Node id.
     */
    id: string;
    /**
     * Whether the node has the ingest role.
     */
    ingest: boolean;
    ip: unknown;
    jvm_version: unknown;
    /**
     * 1-minute load average.
     */
    load_average: unknown;
    /**
     * Whether the node is master-eligible.
     */
    master: boolean;
    /**
     * Node name.
     */
    name: unknown;
};

export type OverviewRelocateInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Source node.
     */
    from: string;
    /**
     * Destination node.
     */
    to: string;
};

export type OverviewShardKindInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Allocation kind to keep enabled, e.g. "primaries" or "none".
     */
    kind: string;
};

export type RawResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Raw Elasticsearch response payload.
     */
    data: unknown;
};

export type RepositoriesCreateInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Repository settings, type-specific.
     */
    settings: unknown;
    /**
     * Repository type (fs, s3, url, ...).
     */
    type: string;
};

export type Repository = {
    /**
     * Repository name.
     */
    name: string;
    /**
     * Repository settings, type-specific.
     */
    settings: unknown;
    /**
     * Repository type (fs, s3, url, ...).
     */
    type: string;
};

export type RestRequestInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    data?: unknown;
    method: string;
    path: string;
};

export type RestRequestResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Raw Elasticsearch response payload.
     */
    data: unknown;
    /**
     * HTTP status returned by Elasticsearch.
     */
    status: number;
};

export type SnapshotsCreateInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    ignoreUnavailable: boolean;
    includeGlobalState: boolean;
    indices?: Array<string> | null;
};

export type SnapshotsRestoreInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    ignoreUnavailable: boolean;
    includeAliases: boolean;
    includeGlobalState: boolean;
    indices?: Array<string> | null;
    renamePattern?: string;
    renameReplacement?: string;
};

export type Template = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Template kind: index, component, or legacy.
     */
    kind: string;
    /**
     * Template name.
     */
    name: string;
    /**
     * Raw template definition.
     */
    template: unknown;
};

export type TemplateSummary = {
    /**
     * Template kind: index, component, or legacy.
     */
    kind: string;
    /**
     * Whether the template appears to be managed by Elasticsearch or an integration.
     */
    managed: boolean;
    /**
     * Template name.
     */
    name: string;
    /**
     * Template index pattern, when applicable.
     */
    pattern?: string;
};

export type AliasesUpdateInBodyWritable = {
    /**
     * Alias actions in Elasticsearch _aliases format, e.g. {"add": {...}} / {"remove": {...}}.
     */
    changes?: Array<unknown> | null;
};

export type AnalysisAnalyzerInBodyWritable = {
    /**
     * Analyzer name.
     */
    analyzer: string;
    /**
     * Text to analyze.
     */
    text: string;
};

export type AnalysisFieldInBodyWritable = {
    /**
     * Field name.
     */
    field: string;
    /**
     * Text to analyze.
     */
    text: string;
};

export type ChangesWritable = {
    /**
     * Cluster name.
     */
    cluster_name: unknown;
    /**
     * All index names, including closed indices.
     */
    indices: Array<string> | null;
    /**
     * Distinct node names.
     */
    nodes: Array<unknown> | null;
};

export type DataExplorerResultWritable = {
    /**
     * Columns discovered from the current result page.
     */
    columns: Array<string> | null;
    /**
     * Flattened documents for tabular display.
     */
    rows: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Total matching documents reported by Elasticsearch.
     */
    total: number;
};

export type DataExplorerSaveInBodyWritable = {
    /**
     * Document _source JSON object.
     */
    document: unknown;
    /**
     * Optional document id. Empty creates a new document id.
     */
    id?: string;
};

export type DataExplorerSearchInBodyWritable = {
    /**
     * Zero-based page number.
     */
    page?: number;
    /**
     * Optional simple query string.
     */
    query?: string;
    /**
     * Query language mode. KQL is the Kibana-like default; Lucene maps to Elasticsearch query_string syntax.
     */
    query_mode?: 'kql' | 'lucene';
    /**
     * Rows per page.
     */
    size?: number;
    /**
     * Optional field to sort by.
     */
    sort_field?: string;
    /**
     * Sort direction.
     */
    sort_order?: 'asc' | 'desc';
};

export type DataStreamWritable = {
    backing_indices: Array<DataStreamBackingIndex> | null;
    backing_indices_count: number;
    generation: number;
    hidden: boolean;
    lifecycle?: unknown;
    managed_by?: string;
    maximum_timestamp?: unknown;
    name: string;
    next_generation_managed_by?: string;
    prefer_ilm: boolean;
    rollover_on_write: boolean;
    status?: string;
    store_size_bytes: number;
    system: boolean;
    template?: string;
    timestamp_field?: string;
};

export type DataStreamAttachIlmInBodyWritable = {
    /**
     * ILM policy name.
     */
    policy: string;
    /**
     * Whether to rollover the data stream after updating the template.
     */
    rollover: boolean;
    /**
     * Whether existing backing indices should get index.lifecycle.name.
     */
    update_backing_indices: boolean;
};

export type DataStreamAttachIlmResultWritable = {
    backing_indices_updated: boolean;
    data_stream: string;
    policy: string;
    rolled_over: boolean;
    template: string;
    template_updated: boolean;
};

export type DataStreamDetachIlmResultWritable = {
    backing_indices_updated: boolean;
    data_stream: string;
    template: string;
    template_updated: boolean;
};

export type DataStreamLifecycleInBodyWritable = {
    /**
     * Data stream lifecycle body.
     */
    lifecycle: unknown;
};

export type DataStreamsResultWritable = {
    /**
     * Data streams.
     */
    items: Array<DataStreamWritable> | null;
    /**
     * Whether the target Elasticsearch supports data streams.
     */
    supported: boolean;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HostBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
};

export type IlmPolicySaveInBodyWritable = {
    /**
     * ILM policy body.
     */
    policy: unknown;
};

export type ListAliasWritable = {
    /**
     * Collection items.
     */
    items: Array<Alias> | null;
};

export type ListHostRefWritable = {
    /**
     * Collection items.
     */
    items: Array<HostRef> | null;
};

export type ListIlmPolicyWritable = {
    /**
     * Collection items.
     */
    items: Array<IlmPolicy> | null;
};

export type ListNodeWritable = {
    /**
     * Collection items.
     */
    items: Array<Node> | null;
};

export type ListRepositoryWritable = {
    /**
     * Collection items.
     */
    items: Array<Repository> | null;
};

export type ListStringWritable = {
    /**
     * Collection items.
     */
    items: Array<string> | null;
};

export type ListTemplateSummaryWritable = {
    /**
     * Collection items.
     */
    items: Array<TemplateSummary> | null;
};

export type MetadataWritable = {
    /**
     * Index mappings (null when not found).
     */
    mappings: unknown;
    /**
     * Index settings (null when not found).
     */
    settings: unknown;
};

export type OverviewWritable = {
    active_primary_shards: unknown;
    active_shards: unknown;
    closed_indices: number;
    /**
     * Cluster name.
     */
    cluster_name: unknown;
    /**
     * Total primary docs count.
     */
    docs_count: unknown;
    indices: Array<OverviewIndex> | null;
    initializing_shards: unknown;
    nodes: Array<OverviewNode> | null;
    /**
     * Number of nodes in the cluster.
     */
    number_of_nodes: unknown;
    relocating_shards: unknown;
    /**
     * Whether shard allocation is enabled (cluster.routing.allocation.enable == all).
     */
    shard_allocation: boolean;
    /**
     * Total store size in bytes.
     */
    size_in_bytes: unknown;
    /**
     * Number of dot-prefixed (system) indices.
     */
    special_indices: number;
    /**
     * Cluster health status (green/yellow/red).
     */
    status: unknown;
    total_indices: number;
    unassigned_shards: unknown;
};

export type OverviewRelocateInBodyWritable = {
    /**
     * Source node.
     */
    from: string;
    /**
     * Destination node.
     */
    to: string;
};

export type OverviewShardKindInBodyWritable = {
    /**
     * Allocation kind to keep enabled, e.g. "primaries" or "none".
     */
    kind: string;
};

export type RawResponseWritable = {
    /**
     * Raw Elasticsearch response payload.
     */
    data: unknown;
};

export type RepositoriesCreateInBodyWritable = {
    /**
     * Repository settings, type-specific.
     */
    settings: unknown;
    /**
     * Repository type (fs, s3, url, ...).
     */
    type: string;
};

export type RestRequestInBodyWritable = {
    data?: unknown;
    method: string;
    path: string;
};

export type RestRequestResponseWritable = {
    /**
     * Raw Elasticsearch response payload.
     */
    data: unknown;
    /**
     * HTTP status returned by Elasticsearch.
     */
    status: number;
};

export type SnapshotsCreateInBodyWritable = {
    ignoreUnavailable: boolean;
    includeGlobalState: boolean;
    indices?: Array<string> | null;
};

export type SnapshotsRestoreInBodyWritable = {
    ignoreUnavailable: boolean;
    includeAliases: boolean;
    includeGlobalState: boolean;
    indices?: Array<string> | null;
    renamePattern?: string;
    renameReplacement?: string;
};

export type TemplateWritable = {
    /**
     * Template kind: index, component, or legacy.
     */
    kind: string;
    /**
     * Template name.
     */
    name: string;
    /**
     * Raw template definition.
     */
    template: unknown;
};

export type AliasesGetData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/aliases';
};

export type AliasesGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AliasesGetError = AliasesGetErrors[keyof AliasesGetErrors];

export type AliasesGetResponses = {
    /**
     * OK
     */
    200: ListAlias;
};

export type AliasesGetResponse = AliasesGetResponses[keyof AliasesGetResponses];

export type AliasesUpdateData = {
    body: AliasesUpdateInBodyWritable;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/aliases';
};

export type AliasesUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AliasesUpdateError = AliasesUpdateErrors[keyof AliasesUpdateErrors];

export type AliasesUpdateResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type AliasesUpdateResponse = AliasesUpdateResponses[keyof AliasesUpdateResponses];

export type AnalysisIndicesData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/analysis/indices';
};

export type AnalysisIndicesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalysisIndicesError = AnalysisIndicesErrors[keyof AnalysisIndicesErrors];

export type AnalysisIndicesResponses = {
    /**
     * OK
     */
    200: ListString;
};

export type AnalysisIndicesResponse = AnalysisIndicesResponses[keyof AnalysisIndicesResponses];

export type AnalysisAnalyzersData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Index name.
         */
        index: string;
    };
    query?: never;
    url: '/clusters/{cluster}/analysis/indices/{index}/analyzers';
};

export type AnalysisAnalyzersErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalysisAnalyzersError = AnalysisAnalyzersErrors[keyof AnalysisAnalyzersErrors];

export type AnalysisAnalyzersResponses = {
    /**
     * OK
     */
    200: ListString;
};

export type AnalysisAnalyzersResponse = AnalysisAnalyzersResponses[keyof AnalysisAnalyzersResponses];

export type AnalysisAnalyzeAnalyzerData = {
    body: AnalysisAnalyzerInBodyWritable;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Index name.
         */
        index: string;
    };
    query?: never;
    url: '/clusters/{cluster}/analysis/indices/{index}/analyzers/_analyze';
};

export type AnalysisAnalyzeAnalyzerErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalysisAnalyzeAnalyzerError = AnalysisAnalyzeAnalyzerErrors[keyof AnalysisAnalyzeAnalyzerErrors];

export type AnalysisAnalyzeAnalyzerResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type AnalysisAnalyzeAnalyzerResponse = AnalysisAnalyzeAnalyzerResponses[keyof AnalysisAnalyzeAnalyzerResponses];

export type AnalysisFieldsData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Index name.
         */
        index: string;
    };
    query?: never;
    url: '/clusters/{cluster}/analysis/indices/{index}/fields';
};

export type AnalysisFieldsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalysisFieldsError = AnalysisFieldsErrors[keyof AnalysisFieldsErrors];

export type AnalysisFieldsResponses = {
    /**
     * OK
     */
    200: ListString;
};

export type AnalysisFieldsResponse = AnalysisFieldsResponses[keyof AnalysisFieldsResponses];

export type AnalysisAnalyzeFieldData = {
    body: AnalysisFieldInBodyWritable;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Index name.
         */
        index: string;
    };
    query?: never;
    url: '/clusters/{cluster}/analysis/indices/{index}/fields/_analyze';
};

export type AnalysisAnalyzeFieldErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalysisAnalyzeFieldError = AnalysisAnalyzeFieldErrors[keyof AnalysisAnalyzeFieldErrors];

export type AnalysisAnalyzeFieldResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type AnalysisAnalyzeFieldResponse = AnalysisAnalyzeFieldResponses[keyof AnalysisAnalyzeFieldResponses];

export type CatData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Name of the _cat API to call, e.g. "indices", "shards", "allocation".
         */
        api: string;
    };
    query?: never;
    url: '/clusters/{cluster}/cat/{api}';
};

export type CatErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CatError = CatErrors[keyof CatErrors];

export type CatResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type CatResponse = CatResponses[keyof CatResponses];

export type ClusterChangesData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/cluster_changes';
};

export type ClusterChangesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ClusterChangesError = ClusterChangesErrors[keyof ClusterChangesErrors];

export type ClusterChangesResponses = {
    /**
     * OK
     */
    200: Changes;
};

export type ClusterChangesResponse = ClusterChangesResponses[keyof ClusterChangesResponses];

export type ClusterSettingsGetData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/cluster_settings';
};

export type ClusterSettingsGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ClusterSettingsGetError = ClusterSettingsGetErrors[keyof ClusterSettingsGetErrors];

export type ClusterSettingsGetResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type ClusterSettingsGetResponse = ClusterSettingsGetResponses[keyof ClusterSettingsGetResponses];

export type ClusterSettingsSaveData = {
    /**
     * Cluster settings document to PUT to _cluster/settings.
     */
    body: unknown;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/cluster_settings';
};

export type ClusterSettingsSaveErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ClusterSettingsSaveError = ClusterSettingsSaveErrors[keyof ClusterSettingsSaveErrors];

export type ClusterSettingsSaveResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type ClusterSettingsSaveResponse = ClusterSettingsSaveResponses[keyof ClusterSettingsSaveResponses];

export type CommonsIndicesData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/commons/indices';
};

export type CommonsIndicesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CommonsIndicesError = CommonsIndicesErrors[keyof CommonsIndicesErrors];

export type CommonsIndicesResponses = {
    /**
     * OK
     */
    200: ListString;
};

export type CommonsIndicesResponse = CommonsIndicesResponses[keyof CommonsIndicesResponses];

export type CommonsGetIndexMappingData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Index name.
         */
        index: string;
    };
    query?: never;
    url: '/clusters/{cluster}/commons/indices/{index}/mapping';
};

export type CommonsGetIndexMappingErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CommonsGetIndexMappingError = CommonsGetIndexMappingErrors[keyof CommonsGetIndexMappingErrors];

export type CommonsGetIndexMappingResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type CommonsGetIndexMappingResponse = CommonsGetIndexMappingResponses[keyof CommonsGetIndexMappingResponses];

export type CommonsGetIndexSettingsData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Index name.
         */
        index: string;
    };
    query?: never;
    url: '/clusters/{cluster}/commons/indices/{index}/settings';
};

export type CommonsGetIndexSettingsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CommonsGetIndexSettingsError = CommonsGetIndexSettingsErrors[keyof CommonsGetIndexSettingsErrors];

export type CommonsGetIndexSettingsResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type CommonsGetIndexSettingsResponse = CommonsGetIndexSettingsResponses[keyof CommonsGetIndexSettingsResponses];

export type CommonsGetIndexStatsData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Index name.
         */
        index: string;
    };
    query?: never;
    url: '/clusters/{cluster}/commons/indices/{index}/stats';
};

export type CommonsGetIndexStatsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CommonsGetIndexStatsError = CommonsGetIndexStatsErrors[keyof CommonsGetIndexStatsErrors];

export type CommonsGetIndexStatsResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type CommonsGetIndexStatsResponse = CommonsGetIndexStatsResponses[keyof CommonsGetIndexStatsResponses];

export type CommonsNodesData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/commons/nodes';
};

export type CommonsNodesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CommonsNodesError = CommonsNodesErrors[keyof CommonsNodesErrors];

export type CommonsNodesResponses = {
    /**
     * OK
     */
    200: ListString;
};

export type CommonsNodesResponse = CommonsNodesResponses[keyof CommonsNodesResponses];

export type CommonsGetNodeStatsData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Node name or id.
         */
        node: string;
    };
    query?: never;
    url: '/clusters/{cluster}/commons/nodes/{node}/stats';
};

export type CommonsGetNodeStatsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CommonsGetNodeStatsError = CommonsGetNodeStatsErrors[keyof CommonsGetNodeStatsErrors];

export type CommonsGetNodeStatsResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type CommonsGetNodeStatsResponse = CommonsGetNodeStatsResponses[keyof CommonsGetNodeStatsResponses];

export type CreateIndexCreateData = {
    /**
     * Index creation body (settings, mappings, aliases). Defaults to {}.
     */
    body: unknown;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Name of the index to create.
         */
        index: string;
    };
    query?: never;
    url: '/clusters/{cluster}/create_index/{index}';
};

export type CreateIndexCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateIndexCreateError = CreateIndexCreateErrors[keyof CreateIndexCreateErrors];

export type CreateIndexCreateResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type CreateIndexCreateResponse = CreateIndexCreateResponses[keyof CreateIndexCreateResponses];

export type CreateIndexGetMetadataData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Index to copy mappings/settings from.
         */
        index: string;
    };
    query?: never;
    url: '/clusters/{cluster}/create_index/{index}/metadata';
};

export type CreateIndexGetMetadataErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateIndexGetMetadataError = CreateIndexGetMetadataErrors[keyof CreateIndexGetMetadataErrors];

export type CreateIndexGetMetadataResponses = {
    /**
     * OK
     */
    200: Metadata;
};

export type CreateIndexGetMetadataResponse = CreateIndexGetMetadataResponses[keyof CreateIndexGetMetadataResponses];

export type DataExplorerSaveData = {
    body: DataExplorerSaveInBodyWritable;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Index name.
         */
        index: string;
    };
    query?: never;
    url: '/clusters/{cluster}/data_explorer/{index}/documents';
};

export type DataExplorerSaveErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DataExplorerSaveError = DataExplorerSaveErrors[keyof DataExplorerSaveErrors];

export type DataExplorerSaveResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type DataExplorerSaveResponse = DataExplorerSaveResponses[keyof DataExplorerSaveResponses];

export type DataExplorerSearchData = {
    body: DataExplorerSearchInBodyWritable;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Index name.
         */
        index: string;
    };
    query?: never;
    url: '/clusters/{cluster}/data_explorer/{index}/search';
};

export type DataExplorerSearchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DataExplorerSearchError = DataExplorerSearchErrors[keyof DataExplorerSearchErrors];

export type DataExplorerSearchResponses = {
    /**
     * OK
     */
    200: DataExplorerResult;
};

export type DataExplorerSearchResponse = DataExplorerSearchResponses[keyof DataExplorerSearchResponses];

export type DataStreamsListData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/data_streams';
};

export type DataStreamsListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DataStreamsListError = DataStreamsListErrors[keyof DataStreamsListErrors];

export type DataStreamsListResponses = {
    /**
     * OK
     */
    200: DataStreamsResult;
};

export type DataStreamsListResponse = DataStreamsListResponses[keyof DataStreamsListResponses];

export type DataStreamsDeleteData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Data stream name.
         */
        name: string;
    };
    query?: never;
    url: '/clusters/{cluster}/data_streams/{name}';
};

export type DataStreamsDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DataStreamsDeleteError = DataStreamsDeleteErrors[keyof DataStreamsDeleteErrors];

export type DataStreamsDeleteResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type DataStreamsDeleteResponse = DataStreamsDeleteResponses[keyof DataStreamsDeleteResponses];

export type DataStreamsGetData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Data stream name.
         */
        name: string;
    };
    query?: never;
    url: '/clusters/{cluster}/data_streams/{name}';
};

export type DataStreamsGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DataStreamsGetError = DataStreamsGetErrors[keyof DataStreamsGetErrors];

export type DataStreamsGetResponses = {
    /**
     * OK
     */
    200: DataStream;
};

export type DataStreamsGetResponse = DataStreamsGetResponses[keyof DataStreamsGetResponses];

export type DataStreamsCreateData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Data stream name.
         */
        name: string;
    };
    query?: never;
    url: '/clusters/{cluster}/data_streams/{name}';
};

export type DataStreamsCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DataStreamsCreateError = DataStreamsCreateErrors[keyof DataStreamsCreateErrors];

export type DataStreamsCreateResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type DataStreamsCreateResponse = DataStreamsCreateResponses[keyof DataStreamsCreateResponses];

export type DataStreamsDetachIlmData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Data stream name.
         */
        name: string;
    };
    query?: {
        /**
         * Whether existing backing indices should have index.lifecycle.name removed.
         */
        update_backing_indices?: boolean;
    };
    url: '/clusters/{cluster}/data_streams/{name}/ilm';
};

export type DataStreamsDetachIlmErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DataStreamsDetachIlmError = DataStreamsDetachIlmErrors[keyof DataStreamsDetachIlmErrors];

export type DataStreamsDetachIlmResponses = {
    /**
     * OK
     */
    200: DataStreamDetachIlmResult;
};

export type DataStreamsDetachIlmResponse = DataStreamsDetachIlmResponses[keyof DataStreamsDetachIlmResponses];

export type DataStreamsAttachIlmData = {
    body: DataStreamAttachIlmInBodyWritable;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Data stream name.
         */
        name: string;
    };
    query?: never;
    url: '/clusters/{cluster}/data_streams/{name}/ilm';
};

export type DataStreamsAttachIlmErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DataStreamsAttachIlmError = DataStreamsAttachIlmErrors[keyof DataStreamsAttachIlmErrors];

export type DataStreamsAttachIlmResponses = {
    /**
     * OK
     */
    200: DataStreamAttachIlmResult;
};

export type DataStreamsAttachIlmResponse = DataStreamsAttachIlmResponses[keyof DataStreamsAttachIlmResponses];

export type DataStreamsUpdateLifecycleData = {
    body: DataStreamLifecycleInBodyWritable;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Data stream name.
         */
        name: string;
    };
    query?: never;
    url: '/clusters/{cluster}/data_streams/{name}/lifecycle';
};

export type DataStreamsUpdateLifecycleErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DataStreamsUpdateLifecycleError = DataStreamsUpdateLifecycleErrors[keyof DataStreamsUpdateLifecycleErrors];

export type DataStreamsUpdateLifecycleResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type DataStreamsUpdateLifecycleResponse = DataStreamsUpdateLifecycleResponses[keyof DataStreamsUpdateLifecycleResponses];

export type DataStreamsRolloverData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Data stream name.
         */
        name: string;
    };
    query?: never;
    url: '/clusters/{cluster}/data_streams/{name}/rollover';
};

export type DataStreamsRolloverErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DataStreamsRolloverError = DataStreamsRolloverErrors[keyof DataStreamsRolloverErrors];

export type DataStreamsRolloverResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type DataStreamsRolloverResponse = DataStreamsRolloverResponses[keyof DataStreamsRolloverResponses];

export type IlmPoliciesListData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/ilm/policies';
};

export type IlmPoliciesListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type IlmPoliciesListError = IlmPoliciesListErrors[keyof IlmPoliciesListErrors];

export type IlmPoliciesListResponses = {
    /**
     * OK
     */
    200: ListIlmPolicy;
};

export type IlmPoliciesListResponse = IlmPoliciesListResponses[keyof IlmPoliciesListResponses];

export type IlmPoliciesDeleteData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * ILM policy name.
         */
        name: string;
    };
    query?: never;
    url: '/clusters/{cluster}/ilm/policies/{name}';
};

export type IlmPoliciesDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type IlmPoliciesDeleteError = IlmPoliciesDeleteErrors[keyof IlmPoliciesDeleteErrors];

export type IlmPoliciesDeleteResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type IlmPoliciesDeleteResponse = IlmPoliciesDeleteResponses[keyof IlmPoliciesDeleteResponses];

export type IlmPoliciesSaveData = {
    body: IlmPolicySaveInBodyWritable;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * ILM policy name.
         */
        name: string;
    };
    query?: never;
    url: '/clusters/{cluster}/ilm/policies/{name}';
};

export type IlmPoliciesSaveErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type IlmPoliciesSaveError = IlmPoliciesSaveErrors[keyof IlmPoliciesSaveErrors];

export type IlmPoliciesSaveResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type IlmPoliciesSaveResponse = IlmPoliciesSaveResponses[keyof IlmPoliciesSaveResponses];

export type IndexSettingsGetData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Index name.
         */
        index: string;
    };
    query?: never;
    url: '/clusters/{cluster}/index_settings/{index}';
};

export type IndexSettingsGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type IndexSettingsGetError = IndexSettingsGetErrors[keyof IndexSettingsGetErrors];

export type IndexSettingsGetResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type IndexSettingsGetResponse = IndexSettingsGetResponses[keyof IndexSettingsGetResponses];

export type IndexSettingsUpdateData = {
    /**
     * Settings document to PUT to the index _settings.
     */
    body: unknown;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Index name.
         */
        index: string;
    };
    query?: never;
    url: '/clusters/{cluster}/index_settings/{index}';
};

export type IndexSettingsUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type IndexSettingsUpdateError = IndexSettingsUpdateErrors[keyof IndexSettingsUpdateErrors];

export type IndexSettingsUpdateResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type IndexSettingsUpdateResponse = IndexSettingsUpdateResponses[keyof IndexSettingsUpdateResponses];

export type NavbarData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/navbar';
};

export type NavbarErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type NavbarError = NavbarErrors[keyof NavbarErrors];

export type NavbarResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type NavbarResponse = NavbarResponses[keyof NavbarResponses];

export type NodesData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/nodes';
};

export type NodesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type NodesError = NodesErrors[keyof NodesErrors];

export type NodesResponses = {
    /**
     * OK
     */
    200: ListNode;
};

export type NodesResponse = NodesResponses[keyof NodesResponses];

export type OverviewData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/overview';
};

export type OverviewErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewError = OverviewErrors[keyof OverviewErrors];

export type OverviewResponses = {
    /**
     * OK
     */
    200: Overview;
};

export type OverviewResponse = OverviewResponses[keyof OverviewResponses];

export type OverviewRelocateShardData = {
    body: OverviewRelocateInBodyWritable;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Index name.
         */
        index: string;
        /**
         * Shard number.
         */
        shard: number;
    };
    query?: never;
    url: '/clusters/{cluster}/overview/indices/{index}/shards/{shard}/relocation';
};

export type OverviewRelocateShardErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewRelocateShardError = OverviewRelocateShardErrors[keyof OverviewRelocateShardErrors];

export type OverviewRelocateShardResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewRelocateShardResponse = OverviewRelocateShardResponses[keyof OverviewRelocateShardResponses];

export type OverviewShardStatsData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Index name.
         */
        index: string;
        /**
         * Shard number.
         */
        shard: number;
    };
    query: {
        /**
         * Node id the shard is allocated on.
         */
        node: string;
    };
    url: '/clusters/{cluster}/overview/indices/{index}/shards/{shard}/stats';
};

export type OverviewShardStatsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewShardStatsError = OverviewShardStatsErrors[keyof OverviewShardStatsErrors];

export type OverviewShardStatsResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewShardStatsResponse = OverviewShardStatsResponses[keyof OverviewShardStatsResponses];

export type OverviewDeleteIndicesData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Comma-separated index names.
         */
        indices: string;
    };
    query?: never;
    url: '/clusters/{cluster}/overview/indices/{indices}';
};

export type OverviewDeleteIndicesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewDeleteIndicesError = OverviewDeleteIndicesErrors[keyof OverviewDeleteIndicesErrors];

export type OverviewDeleteIndicesResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewDeleteIndicesResponse = OverviewDeleteIndicesResponses[keyof OverviewDeleteIndicesResponses];

export type OverviewClearIndicesCacheData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Comma-separated index names.
         */
        indices: string;
    };
    query?: never;
    url: '/clusters/{cluster}/overview/indices/{indices}/cache/clear';
};

export type OverviewClearIndicesCacheErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewClearIndicesCacheError = OverviewClearIndicesCacheErrors[keyof OverviewClearIndicesCacheErrors];

export type OverviewClearIndicesCacheResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewClearIndicesCacheResponse = OverviewClearIndicesCacheResponses[keyof OverviewClearIndicesCacheResponses];

export type OverviewCloseIndicesData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Comma-separated index names.
         */
        indices: string;
    };
    query?: never;
    url: '/clusters/{cluster}/overview/indices/{indices}/close';
};

export type OverviewCloseIndicesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewCloseIndicesError = OverviewCloseIndicesErrors[keyof OverviewCloseIndicesErrors];

export type OverviewCloseIndicesResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewCloseIndicesResponse = OverviewCloseIndicesResponses[keyof OverviewCloseIndicesResponses];

export type OverviewFlushIndicesData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Comma-separated index names.
         */
        indices: string;
    };
    query?: never;
    url: '/clusters/{cluster}/overview/indices/{indices}/flush';
};

export type OverviewFlushIndicesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewFlushIndicesError = OverviewFlushIndicesErrors[keyof OverviewFlushIndicesErrors];

export type OverviewFlushIndicesResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewFlushIndicesResponse = OverviewFlushIndicesResponses[keyof OverviewFlushIndicesResponses];

export type OverviewForceMergeData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Comma-separated index names.
         */
        indices: string;
    };
    query?: never;
    url: '/clusters/{cluster}/overview/indices/{indices}/forcemerge';
};

export type OverviewForceMergeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewForceMergeError = OverviewForceMergeErrors[keyof OverviewForceMergeErrors];

export type OverviewForceMergeResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewForceMergeResponse = OverviewForceMergeResponses[keyof OverviewForceMergeResponses];

export type OverviewOpenIndicesData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Comma-separated index names.
         */
        indices: string;
    };
    query?: never;
    url: '/clusters/{cluster}/overview/indices/{indices}/open';
};

export type OverviewOpenIndicesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewOpenIndicesError = OverviewOpenIndicesErrors[keyof OverviewOpenIndicesErrors];

export type OverviewOpenIndicesResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewOpenIndicesResponse = OverviewOpenIndicesResponses[keyof OverviewOpenIndicesResponses];

export type OverviewRefreshIndicesData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Comma-separated index names.
         */
        indices: string;
    };
    query?: never;
    url: '/clusters/{cluster}/overview/indices/{indices}/refresh';
};

export type OverviewRefreshIndicesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewRefreshIndicesError = OverviewRefreshIndicesErrors[keyof OverviewRefreshIndicesErrors];

export type OverviewRefreshIndicesResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewRefreshIndicesResponse = OverviewRefreshIndicesResponses[keyof OverviewRefreshIndicesResponses];

export type OverviewEnableShardAllocationData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/overview/shard_allocation';
};

export type OverviewEnableShardAllocationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewEnableShardAllocationError = OverviewEnableShardAllocationErrors[keyof OverviewEnableShardAllocationErrors];

export type OverviewEnableShardAllocationResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewEnableShardAllocationResponse = OverviewEnableShardAllocationResponses[keyof OverviewEnableShardAllocationResponses];

export type OverviewDisableShardAllocationData = {
    body: OverviewShardKindInBodyWritable;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/overview/shard_allocation';
};

export type OverviewDisableShardAllocationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewDisableShardAllocationError = OverviewDisableShardAllocationErrors[keyof OverviewDisableShardAllocationErrors];

export type OverviewDisableShardAllocationResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewDisableShardAllocationResponse = OverviewDisableShardAllocationResponses[keyof OverviewDisableShardAllocationResponses];

export type RepositoriesListData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/repositories';
};

export type RepositoriesListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RepositoriesListError = RepositoriesListErrors[keyof RepositoriesListErrors];

export type RepositoriesListResponses = {
    /**
     * OK
     */
    200: ListRepository;
};

export type RepositoriesListResponse = RepositoriesListResponses[keyof RepositoriesListResponses];

export type RepositoriesDeleteData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Repository name.
         */
        name: string;
    };
    query?: never;
    url: '/clusters/{cluster}/repositories/{name}';
};

export type RepositoriesDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RepositoriesDeleteError = RepositoriesDeleteErrors[keyof RepositoriesDeleteErrors];

export type RepositoriesDeleteResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type RepositoriesDeleteResponse = RepositoriesDeleteResponses[keyof RepositoriesDeleteResponses];

export type RepositoriesCreateData = {
    body: RepositoriesCreateInBodyWritable;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Repository name.
         */
        name: string;
    };
    query?: never;
    url: '/clusters/{cluster}/repositories/{name}';
};

export type RepositoriesCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RepositoriesCreateError = RepositoriesCreateErrors[keyof RepositoriesCreateErrors];

export type RepositoriesCreateResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type RepositoriesCreateResponse = RepositoriesCreateResponses[keyof RepositoriesCreateResponses];

export type RestIndexData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/rest';
};

export type RestIndexErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RestIndexError = RestIndexErrors[keyof RestIndexErrors];

export type RestIndexResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type RestIndexResponse = RestIndexResponses[keyof RestIndexResponses];

export type RestHistoryData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/rest/history';
};

export type RestHistoryErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RestHistoryError = RestHistoryErrors[keyof RestHistoryErrors];

export type RestHistoryResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type RestHistoryResponse = RestHistoryResponses[keyof RestHistoryResponses];

export type RestRequestData = {
    body: RestRequestInBodyWritable;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/rest/requests';
};

export type RestRequestErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RestRequestError = RestRequestErrors[keyof RestRequestErrors];

export type RestRequestResponses = {
    /**
     * OK
     */
    200: RestRequestResponse;
};

export type RestRequestResponse2 = RestRequestResponses[keyof RestRequestResponses];

export type SnapshotsGetData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/snapshots';
};

export type SnapshotsGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SnapshotsGetError = SnapshotsGetErrors[keyof SnapshotsGetErrors];

export type SnapshotsGetResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type SnapshotsGetResponse = SnapshotsGetResponses[keyof SnapshotsGetResponses];

export type SnapshotsLoadData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Repository name.
         */
        repository: string;
    };
    query?: never;
    url: '/clusters/{cluster}/snapshots/{repository}';
};

export type SnapshotsLoadErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SnapshotsLoadError = SnapshotsLoadErrors[keyof SnapshotsLoadErrors];

export type SnapshotsLoadResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type SnapshotsLoadResponse = SnapshotsLoadResponses[keyof SnapshotsLoadResponses];

export type SnapshotsDeleteData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Repository name.
         */
        repository: string;
        /**
         * Snapshot name.
         */
        snapshot: string;
    };
    query?: never;
    url: '/clusters/{cluster}/snapshots/{repository}/{snapshot}';
};

export type SnapshotsDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SnapshotsDeleteError = SnapshotsDeleteErrors[keyof SnapshotsDeleteErrors];

export type SnapshotsDeleteResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type SnapshotsDeleteResponse = SnapshotsDeleteResponses[keyof SnapshotsDeleteResponses];

export type SnapshotsCreateData = {
    body: SnapshotsCreateInBodyWritable;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Repository name.
         */
        repository: string;
        /**
         * Snapshot name.
         */
        snapshot: string;
    };
    query?: never;
    url: '/clusters/{cluster}/snapshots/{repository}/{snapshot}';
};

export type SnapshotsCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SnapshotsCreateError = SnapshotsCreateErrors[keyof SnapshotsCreateErrors];

export type SnapshotsCreateResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type SnapshotsCreateResponse = SnapshotsCreateResponses[keyof SnapshotsCreateResponses];

export type SnapshotsRestoreData = {
    body: SnapshotsRestoreInBodyWritable;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Repository name.
         */
        repository: string;
        /**
         * Snapshot name.
         */
        snapshot: string;
    };
    query?: never;
    url: '/clusters/{cluster}/snapshots/{repository}/{snapshot}/restore';
};

export type SnapshotsRestoreErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SnapshotsRestoreError = SnapshotsRestoreErrors[keyof SnapshotsRestoreErrors];

export type SnapshotsRestoreResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type SnapshotsRestoreResponse = SnapshotsRestoreResponses[keyof SnapshotsRestoreResponses];

export type TemplatesListData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
    };
    query?: never;
    url: '/clusters/{cluster}/templates';
};

export type TemplatesListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TemplatesListError = TemplatesListErrors[keyof TemplatesListErrors];

export type TemplatesListResponses = {
    /**
     * OK
     */
    200: ListTemplateSummary;
};

export type TemplatesListResponse = TemplatesListResponses[keyof TemplatesListResponses];

export type TemplatesDeleteData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Template kind.
         */
        kind: 'index' | 'component' | 'legacy';
        /**
         * Template name.
         */
        name: string;
    };
    query?: never;
    url: '/clusters/{cluster}/templates/{kind}/{name}';
};

export type TemplatesDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TemplatesDeleteError = TemplatesDeleteErrors[keyof TemplatesDeleteErrors];

export type TemplatesDeleteResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type TemplatesDeleteResponse = TemplatesDeleteResponses[keyof TemplatesDeleteResponses];

export type TemplatesGetData = {
    body?: never;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Template kind.
         */
        kind: 'index' | 'component' | 'legacy';
        /**
         * Template name.
         */
        name: string;
    };
    query?: never;
    url: '/clusters/{cluster}/templates/{kind}/{name}';
};

export type TemplatesGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TemplatesGetError = TemplatesGetErrors[keyof TemplatesGetErrors];

export type TemplatesGetResponses = {
    /**
     * OK
     */
    200: Template;
};

export type TemplatesGetResponse = TemplatesGetResponses[keyof TemplatesGetResponses];

export type TemplatesCreateData = {
    /**
     * Raw template definition.
     */
    body: unknown;
    path: {
        /**
         * Configured Elasticsearch host slug.
         */
        cluster: string;
        /**
         * Template kind.
         */
        kind: 'index' | 'component' | 'legacy';
        /**
         * Template name.
         */
        name: string;
    };
    query?: never;
    url: '/clusters/{cluster}/templates/{kind}/{name}';
};

export type TemplatesCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TemplatesCreateError = TemplatesCreateErrors[keyof TemplatesCreateErrors];

export type TemplatesCreateResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type TemplatesCreateResponse = TemplatesCreateResponses[keyof TemplatesCreateResponses];

export type ConnectData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/connect';
};

export type ConnectErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ConnectError = ConnectErrors[keyof ConnectErrors];

export type ConnectResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type ConnectResponse = ConnectResponses[keyof ConnectResponses];

export type ConnectHostsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connect/hosts';
};

export type ConnectHostsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ConnectHostsError = ConnectHostsErrors[keyof ConnectHostsErrors];

export type ConnectHostsResponses = {
    /**
     * OK
     */
    200: ListHostRef;
};

export type ConnectHostsResponse = ConnectHostsResponses[keyof ConnectHostsResponses];
