// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Alias = {
    /**
     * Alias name.
     */
    alias: string;
    /**
     * Optional alias filter query (null when absent).
     */
    filter: unknown;
    /**
     * Index the alias points at.
     */
    index: string;
    /**
     * Optional index routing value (null when absent).
     */
    index_routing: unknown;
    /**
     * Optional search routing value (null when absent).
     */
    search_routing: unknown;
};

export type AliasesUpdateInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Alias actions in Elasticsearch _aliases format, e.g. {"add": {...}} / {"remove": {...}}.
     */
    changes?: Array<unknown> | null;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type AnalysisAnalyzerInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Analyzer name.
     */
    analyzer: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Text to analyze.
     */
    text: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type AnalysisFieldInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Field name.
     */
    field: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Text to analyze.
     */
    text: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type AnalysisIndexInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type CatInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the _cat API to call, e.g. "indices", "shards", "allocation".
     */
    api: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type Changes = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Cluster name.
     */
    cluster_name: unknown;
    /**
     * All index names, including closed indices.
     */
    indices: Array<string> | null;
    /**
     * Distinct node names.
     */
    nodes: Array<unknown> | null;
};

export type ClusterSettingsSaveInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Cluster settings document to PUT to _cluster/settings.
     */
    settings: unknown;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type CommonsIndexInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type CommonsNodeInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Node name or id.
     */
    node: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type CreateIndexCreateInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Name of the index to create.
     */
    index: string;
    /**
     * Index creation body (settings, mappings, aliases). Defaults to {}.
     */
    metadata?: unknown;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type CreateIndexGetMetaInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index to copy mappings/settings from.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type DataExplorerResult = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Columns discovered from the current result page.
     */
    columns: Array<string> | null;
    /**
     * Flattened documents for tabular display.
     */
    rows: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Total matching documents reported by Elasticsearch.
     */
    total: number;
};

export type DataExplorerSaveInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Document _source JSON object.
     */
    document: unknown;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Optional document id. Empty creates a new document id.
     */
    id?: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type DataExplorerSearchInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Zero-based page number.
     */
    page?: number;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional simple query string.
     */
    query?: string;
    /**
     * Query language mode. KQL is the Kibana-like default; Lucene maps to Elasticsearch query_string syntax.
     */
    query_mode?: 'kql' | 'lucene';
    /**
     * Rows per page.
     */
    size?: number;
    /**
     * Optional field to sort by.
     */
    sort_field?: string;
    /**
     * Sort direction.
     */
    sort_order?: 'asc' | 'desc';
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HostBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type IndexSettingsGetInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type IndexSettingsUpdateInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Settings document to PUT to the index _settings.
     */
    settings: unknown;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type ListAlias = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Collection items.
     */
    items: Array<Alias> | null;
};

export type ListNode = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Collection items.
     */
    items: Array<Node> | null;
};

export type ListRepository = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Collection items.
     */
    items: Array<Repository> | null;
};

export type ListString = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Collection items.
     */
    items: Array<string> | null;
};

export type ListTemplate = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Collection items.
     */
    items: Array<Template> | null;
};

export type Metadata = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Index mappings (null when not found).
     */
    mappings: unknown;
    /**
     * Index settings (null when not found).
     */
    settings: unknown;
};

export type Node = {
    /**
     * Custom node attributes (internal ES attributes filtered out).
     */
    attributes: {
        [key: string]: unknown;
    };
    /**
     * Whether the node is a coordinating-only node.
     */
    coordinating: boolean;
    cpu: NodeCpu;
    /**
     * Whether this node is the elected master.
     */
    current_master: boolean;
    /**
     * Whether the node has a data role.
     */
    data: boolean;
    /**
     * Disk usage (null when filesystem stats are unavailable).
     */
    disk: NodeDisk;
    heap: NodeHeap;
    /**
     * Node host.
     */
    host: unknown;
    /**
     * Node id.
     */
    id: string;
    /**
     * Whether the node has the ingest role.
     */
    ingest: boolean;
    /**
     * JVM version.
     */
    jvm: unknown;
    /**
     * Whether the node is master-eligible.
     */
    master: boolean;
    /**
     * Node name.
     */
    name: unknown;
    /**
     * JVM uptime in milliseconds.
     */
    uptime: unknown;
    /**
     * Elasticsearch version.
     */
    version: unknown;
};

export type NodeCpu = {
    /**
     * 1-minute load average.
     */
    load: unknown;
    /**
     * OS CPU usage percentage.
     */
    os: unknown;
    /**
     * Process CPU usage percentage.
     */
    process: unknown;
};

export type NodeDisk = {
    /**
     * Available filesystem size in bytes.
     */
    available: number;
    /**
     * Used disk percentage.
     */
    percent: number;
    /**
     * Total filesystem size in bytes.
     */
    total: number;
};

export type NodeHeap = {
    /**
     * Maximum JVM heap.
     */
    max: unknown;
    /**
     * Used JVM heap percentage.
     */
    percent: unknown;
    /**
     * Used JVM heap.
     */
    used: unknown;
};

export type Overview = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    active_primary_shards: unknown;
    active_shards: unknown;
    closed_indices: number;
    /**
     * Cluster name.
     */
    cluster_name: unknown;
    /**
     * Total primary docs count.
     */
    docs_count: unknown;
    indices: Array<OverviewIndex> | null;
    initializing_shards: unknown;
    nodes: Array<OverviewNode> | null;
    /**
     * Number of nodes in the cluster.
     */
    number_of_nodes: unknown;
    relocating_shards: unknown;
    /**
     * Whether shard allocation is enabled (cluster.routing.allocation.enable == all).
     */
    shard_allocation: boolean;
    /**
     * Total store size in bytes.
     */
    size_in_bytes: unknown;
    /**
     * Number of dot-prefixed (system) indices.
     */
    special_indices: number;
    /**
     * Cluster health status (green/yellow/red).
     */
    status: unknown;
    total_indices: number;
    unassigned_shards: unknown;
};

export type OverviewDisk = {
    /**
     * Free filesystem size in bytes.
     */
    free: number;
    /**
     * Total filesystem size in bytes.
     */
    total: number;
    used_percent: number;
};

export type OverviewHeap = {
    /**
     * Committed JVM heap in bytes.
     */
    committed: unknown;
    /**
     * Maximum JVM heap in bytes.
     */
    max: unknown;
    /**
     * Used JVM heap in bytes.
     */
    used: unknown;
    used_percent: unknown;
};

export type OverviewIndex = {
    aliases: Array<string> | null;
    closed: boolean;
    deleted_docs: unknown;
    doc_count: unknown;
    /**
     * Index name.
     */
    name: string;
    num_replicas: number;
    num_shards: number;
    /**
     * Routing table shards grouped by node name ('unassigned' for unassigned shards).
     */
    shards: {
        [key: string]: Array<{
            [key: string]: unknown;
        }> | null;
    };
    /**
     * Primary store size in bytes.
     */
    size_in_bytes: unknown;
    /**
     * Whether the index is dot-prefixed (system index).
     */
    special: boolean;
    total_size_in_bytes: unknown;
    /**
     * Whether any shard is not STARTED.
     */
    unhealthy: boolean;
};

export type OverviewIndicesInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Comma-separated index names.
     */
    indices: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type OverviewNode = {
    /**
     * Custom node attributes (internal ES attributes filtered out).
     */
    attributes: {
        [key: string]: unknown;
    };
    available_processors: unknown;
    /**
     * Whether the node is a coordinating-only node.
     */
    coordinating: boolean;
    cpu_percent: unknown;
    /**
     * Whether this node is the elected master.
     */
    current_master: boolean;
    /**
     * Whether the node has a data role.
     */
    data: boolean;
    disk: OverviewDisk;
    /**
     * Elasticsearch version.
     */
    es_version: unknown;
    heap: OverviewHeap;
    host: unknown;
    /**
     * Node id.
     */
    id: string;
    /**
     * Whether the node has the ingest role.
     */
    ingest: boolean;
    ip: unknown;
    jvm_version: unknown;
    /**
     * 1-minute load average.
     */
    load_average: unknown;
    /**
     * Whether the node is master-eligible.
     */
    master: boolean;
    /**
     * Node name.
     */
    name: unknown;
};

export type OverviewRelocateInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Source node.
     */
    from: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Shard number.
     */
    shard: number;
    /**
     * Destination node.
     */
    to: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type OverviewShardKindInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Allocation kind to keep enabled, e.g. "primaries" or "none".
     */
    kind: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type OverviewShardStatsInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Node id the shard is allocated on.
     */
    node: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Shard number.
     */
    shard: number;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type RawResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Raw Elasticsearch response payload.
     */
    data: unknown;
};

export type RepositoriesCreateInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Repository name.
     */
    name: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Repository settings, type-specific.
     */
    settings: unknown;
    /**
     * Repository type (fs, s3, url, ...).
     */
    type: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type RepositoriesDeleteInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Repository name.
     */
    name: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type Repository = {
    /**
     * Repository name.
     */
    name: string;
    /**
     * Repository settings, type-specific.
     */
    settings: unknown;
    /**
     * Repository type (fs, s3, url, ...).
     */
    type: string;
};

export type RestRequestInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    data?: unknown;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    method: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    path: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type RestRequestResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Raw Elasticsearch response payload.
     */
    data: unknown;
    /**
     * HTTP status returned by Elasticsearch.
     */
    status: number;
};

export type SnapshotsCreateInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    ignoreUnavailable: boolean;
    includeGlobalState: boolean;
    indices?: Array<string> | null;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    repository: string;
    snapshot: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type SnapshotsDeleteInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    repository: string;
    snapshot: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type SnapshotsLoadInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    repository: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type SnapshotsRestoreInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    ignoreUnavailable: boolean;
    includeAliases: boolean;
    includeGlobalState: boolean;
    indices?: Array<string> | null;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    renamePattern?: string;
    renameReplacement?: string;
    repository: string;
    snapshot: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type Template = {
    /**
     * Template name.
     */
    name: string;
    /**
     * Raw template definition.
     */
    template: unknown;
};

export type TemplatesCreateInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    name: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    template: unknown;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type TemplatesDeleteInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    name: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type AliasesUpdateInBodyWritable = {
    /**
     * Alias actions in Elasticsearch _aliases format, e.g. {"add": {...}} / {"remove": {...}}.
     */
    changes?: Array<unknown> | null;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type AnalysisAnalyzerInBodyWritable = {
    /**
     * Analyzer name.
     */
    analyzer: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Text to analyze.
     */
    text: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type AnalysisFieldInBodyWritable = {
    /**
     * Field name.
     */
    field: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Text to analyze.
     */
    text: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type AnalysisIndexInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type CatInBodyWritable = {
    /**
     * Name of the _cat API to call, e.g. "indices", "shards", "allocation".
     */
    api: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type ChangesWritable = {
    /**
     * Cluster name.
     */
    cluster_name: unknown;
    /**
     * All index names, including closed indices.
     */
    indices: Array<string> | null;
    /**
     * Distinct node names.
     */
    nodes: Array<unknown> | null;
};

export type ClusterSettingsSaveInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Cluster settings document to PUT to _cluster/settings.
     */
    settings: unknown;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type CommonsIndexInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type CommonsNodeInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Node name or id.
     */
    node: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type CreateIndexCreateInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Name of the index to create.
     */
    index: string;
    /**
     * Index creation body (settings, mappings, aliases). Defaults to {}.
     */
    metadata?: unknown;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type CreateIndexGetMetaInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index to copy mappings/settings from.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type DataExplorerResultWritable = {
    /**
     * Columns discovered from the current result page.
     */
    columns: Array<string> | null;
    /**
     * Flattened documents for tabular display.
     */
    rows: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Total matching documents reported by Elasticsearch.
     */
    total: number;
};

export type DataExplorerSaveInBodyWritable = {
    /**
     * Document _source JSON object.
     */
    document: unknown;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Optional document id. Empty creates a new document id.
     */
    id?: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type DataExplorerSearchInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Zero-based page number.
     */
    page?: number;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional simple query string.
     */
    query?: string;
    /**
     * Query language mode. KQL is the Kibana-like default; Lucene maps to Elasticsearch query_string syntax.
     */
    query_mode?: 'kql' | 'lucene';
    /**
     * Rows per page.
     */
    size?: number;
    /**
     * Optional field to sort by.
     */
    sort_field?: string;
    /**
     * Sort direction.
     */
    sort_order?: 'asc' | 'desc';
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HostBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type IndexSettingsGetInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type IndexSettingsUpdateInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Settings document to PUT to the index _settings.
     */
    settings: unknown;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type ListAliasWritable = {
    /**
     * Collection items.
     */
    items: Array<Alias> | null;
};

export type ListNodeWritable = {
    /**
     * Collection items.
     */
    items: Array<Node> | null;
};

export type ListRepositoryWritable = {
    /**
     * Collection items.
     */
    items: Array<Repository> | null;
};

export type ListStringWritable = {
    /**
     * Collection items.
     */
    items: Array<string> | null;
};

export type ListTemplateWritable = {
    /**
     * Collection items.
     */
    items: Array<Template> | null;
};

export type MetadataWritable = {
    /**
     * Index mappings (null when not found).
     */
    mappings: unknown;
    /**
     * Index settings (null when not found).
     */
    settings: unknown;
};

export type OverviewWritable = {
    active_primary_shards: unknown;
    active_shards: unknown;
    closed_indices: number;
    /**
     * Cluster name.
     */
    cluster_name: unknown;
    /**
     * Total primary docs count.
     */
    docs_count: unknown;
    indices: Array<OverviewIndex> | null;
    initializing_shards: unknown;
    nodes: Array<OverviewNode> | null;
    /**
     * Number of nodes in the cluster.
     */
    number_of_nodes: unknown;
    relocating_shards: unknown;
    /**
     * Whether shard allocation is enabled (cluster.routing.allocation.enable == all).
     */
    shard_allocation: boolean;
    /**
     * Total store size in bytes.
     */
    size_in_bytes: unknown;
    /**
     * Number of dot-prefixed (system) indices.
     */
    special_indices: number;
    /**
     * Cluster health status (green/yellow/red).
     */
    status: unknown;
    total_indices: number;
    unassigned_shards: unknown;
};

export type OverviewIndicesInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Comma-separated index names.
     */
    indices: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type OverviewRelocateInBodyWritable = {
    /**
     * Source node.
     */
    from: string;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Shard number.
     */
    shard: number;
    /**
     * Destination node.
     */
    to: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type OverviewShardKindInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Allocation kind to keep enabled, e.g. "primaries" or "none".
     */
    kind: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type OverviewShardStatsInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Index name.
     */
    index: string;
    /**
     * Node id the shard is allocated on.
     */
    node: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Shard number.
     */
    shard: number;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type RawResponseWritable = {
    /**
     * Raw Elasticsearch response payload.
     */
    data: unknown;
};

export type RepositoriesCreateInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Repository name.
     */
    name: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Repository settings, type-specific.
     */
    settings: unknown;
    /**
     * Repository type (fs, s3, url, ...).
     */
    type: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type RepositoriesDeleteInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Repository name.
     */
    name: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type RestRequestInBodyWritable = {
    data?: unknown;
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    method: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    path: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type RestRequestResponseWritable = {
    /**
     * Raw Elasticsearch response payload.
     */
    data: unknown;
    /**
     * HTTP status returned by Elasticsearch.
     */
    status: number;
};

export type SnapshotsCreateInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    ignoreUnavailable: boolean;
    includeGlobalState: boolean;
    indices?: Array<string> | null;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    repository: string;
    snapshot: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type SnapshotsDeleteInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    repository: string;
    snapshot: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type SnapshotsLoadInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    repository: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type SnapshotsRestoreInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    ignoreUnavailable: boolean;
    includeAliases: boolean;
    includeGlobalState: boolean;
    indices?: Array<string> | null;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    renamePattern?: string;
    renameReplacement?: string;
    repository: string;
    snapshot: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type TemplatesCreateInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    name: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    template: unknown;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type TemplatesDeleteInBodyWritable = {
    /**
     * Name of the target Elasticsearch host as configured.
     */
    host: string;
    name: string;
    /**
     * Optional per-request basic auth password override.
     */
    password?: string;
    /**
     * Optional per-request basic auth username override.
     */
    username?: string;
};

export type AliasesGetData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/aliases/get_aliases';
};

export type AliasesGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AliasesGetError = AliasesGetErrors[keyof AliasesGetErrors];

export type AliasesGetResponses = {
    /**
     * OK
     */
    200: ListAlias;
};

export type AliasesGetResponse = AliasesGetResponses[keyof AliasesGetResponses];

export type AliasesUpdateData = {
    body: AliasesUpdateInBodyWritable;
    path?: never;
    query?: never;
    url: '/aliases/update_aliases';
};

export type AliasesUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AliasesUpdateError = AliasesUpdateErrors[keyof AliasesUpdateErrors];

export type AliasesUpdateResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type AliasesUpdateResponse = AliasesUpdateResponses[keyof AliasesUpdateResponses];

export type AnalysisAnalyzeAnalyzerData = {
    body: AnalysisAnalyzerInBodyWritable;
    path?: never;
    query?: never;
    url: '/analysis/analyze/analyzer';
};

export type AnalysisAnalyzeAnalyzerErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalysisAnalyzeAnalyzerError = AnalysisAnalyzeAnalyzerErrors[keyof AnalysisAnalyzeAnalyzerErrors];

export type AnalysisAnalyzeAnalyzerResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type AnalysisAnalyzeAnalyzerResponse = AnalysisAnalyzeAnalyzerResponses[keyof AnalysisAnalyzeAnalyzerResponses];

export type AnalysisAnalyzeFieldData = {
    body: AnalysisFieldInBodyWritable;
    path?: never;
    query?: never;
    url: '/analysis/analyze/field';
};

export type AnalysisAnalyzeFieldErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalysisAnalyzeFieldError = AnalysisAnalyzeFieldErrors[keyof AnalysisAnalyzeFieldErrors];

export type AnalysisAnalyzeFieldResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type AnalysisAnalyzeFieldResponse = AnalysisAnalyzeFieldResponses[keyof AnalysisAnalyzeFieldResponses];

export type AnalysisAnalyzersData = {
    body: AnalysisIndexInBodyWritable;
    path?: never;
    query?: never;
    url: '/analysis/analyzers';
};

export type AnalysisAnalyzersErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalysisAnalyzersError = AnalysisAnalyzersErrors[keyof AnalysisAnalyzersErrors];

export type AnalysisAnalyzersResponses = {
    /**
     * OK
     */
    200: ListString;
};

export type AnalysisAnalyzersResponse = AnalysisAnalyzersResponses[keyof AnalysisAnalyzersResponses];

export type AnalysisFieldsData = {
    body: AnalysisIndexInBodyWritable;
    path?: never;
    query?: never;
    url: '/analysis/fields';
};

export type AnalysisFieldsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalysisFieldsError = AnalysisFieldsErrors[keyof AnalysisFieldsErrors];

export type AnalysisFieldsResponses = {
    /**
     * OK
     */
    200: ListString;
};

export type AnalysisFieldsResponse = AnalysisFieldsResponses[keyof AnalysisFieldsResponses];

export type AnalysisIndicesData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/analysis/indices';
};

export type AnalysisIndicesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalysisIndicesError = AnalysisIndicesErrors[keyof AnalysisIndicesErrors];

export type AnalysisIndicesResponses = {
    /**
     * OK
     */
    200: ListString;
};

export type AnalysisIndicesResponse = AnalysisIndicesResponses[keyof AnalysisIndicesResponses];

export type CatData = {
    body: CatInBodyWritable;
    path?: never;
    query?: never;
    url: '/cat';
};

export type CatErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CatError = CatErrors[keyof CatErrors];

export type CatResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type CatResponse = CatResponses[keyof CatResponses];

export type ClusterChangesData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/cluster_changes';
};

export type ClusterChangesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ClusterChangesError = ClusterChangesErrors[keyof ClusterChangesErrors];

export type ClusterChangesResponses = {
    /**
     * OK
     */
    200: Changes;
};

export type ClusterChangesResponse = ClusterChangesResponses[keyof ClusterChangesResponses];

export type ClusterSettingsGetData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/cluster_settings';
};

export type ClusterSettingsGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ClusterSettingsGetError = ClusterSettingsGetErrors[keyof ClusterSettingsGetErrors];

export type ClusterSettingsGetResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type ClusterSettingsGetResponse = ClusterSettingsGetResponses[keyof ClusterSettingsGetResponses];

export type ClusterSettingsSaveData = {
    body: ClusterSettingsSaveInBodyWritable;
    path?: never;
    query?: never;
    url: '/cluster_settings/save';
};

export type ClusterSettingsSaveErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ClusterSettingsSaveError = ClusterSettingsSaveErrors[keyof ClusterSettingsSaveErrors];

export type ClusterSettingsSaveResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type ClusterSettingsSaveResponse = ClusterSettingsSaveResponses[keyof ClusterSettingsSaveResponses];

export type CommonsGetIndexMappingData = {
    body: CommonsIndexInBodyWritable;
    path?: never;
    query?: never;
    url: '/commons/get_index_mapping';
};

export type CommonsGetIndexMappingErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CommonsGetIndexMappingError = CommonsGetIndexMappingErrors[keyof CommonsGetIndexMappingErrors];

export type CommonsGetIndexMappingResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type CommonsGetIndexMappingResponse = CommonsGetIndexMappingResponses[keyof CommonsGetIndexMappingResponses];

export type CommonsGetIndexSettingsData = {
    body: CommonsIndexInBodyWritable;
    path?: never;
    query?: never;
    url: '/commons/get_index_settings';
};

export type CommonsGetIndexSettingsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CommonsGetIndexSettingsError = CommonsGetIndexSettingsErrors[keyof CommonsGetIndexSettingsErrors];

export type CommonsGetIndexSettingsResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type CommonsGetIndexSettingsResponse = CommonsGetIndexSettingsResponses[keyof CommonsGetIndexSettingsResponses];

export type CommonsGetIndexStatsData = {
    body: CommonsIndexInBodyWritable;
    path?: never;
    query?: never;
    url: '/commons/get_index_stats';
};

export type CommonsGetIndexStatsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CommonsGetIndexStatsError = CommonsGetIndexStatsErrors[keyof CommonsGetIndexStatsErrors];

export type CommonsGetIndexStatsResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type CommonsGetIndexStatsResponse = CommonsGetIndexStatsResponses[keyof CommonsGetIndexStatsResponses];

export type CommonsGetNodeStatsData = {
    body: CommonsNodeInBodyWritable;
    path?: never;
    query?: never;
    url: '/commons/get_node_stats';
};

export type CommonsGetNodeStatsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CommonsGetNodeStatsError = CommonsGetNodeStatsErrors[keyof CommonsGetNodeStatsErrors];

export type CommonsGetNodeStatsResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type CommonsGetNodeStatsResponse = CommonsGetNodeStatsResponses[keyof CommonsGetNodeStatsResponses];

export type CommonsIndicesData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/commons/indices';
};

export type CommonsIndicesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CommonsIndicesError = CommonsIndicesErrors[keyof CommonsIndicesErrors];

export type CommonsIndicesResponses = {
    /**
     * OK
     */
    200: ListString;
};

export type CommonsIndicesResponse = CommonsIndicesResponses[keyof CommonsIndicesResponses];

export type CommonsNodesData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/commons/nodes';
};

export type CommonsNodesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CommonsNodesError = CommonsNodesErrors[keyof CommonsNodesErrors];

export type CommonsNodesResponses = {
    /**
     * OK
     */
    200: ListString;
};

export type CommonsNodesResponse = CommonsNodesResponses[keyof CommonsNodesResponses];

export type ConnectData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/connect';
};

export type ConnectErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ConnectError = ConnectErrors[keyof ConnectErrors];

export type ConnectResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type ConnectResponse = ConnectResponses[keyof ConnectResponses];

export type ConnectHostsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connect/hosts';
};

export type ConnectHostsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ConnectHostsError = ConnectHostsErrors[keyof ConnectHostsErrors];

export type ConnectHostsResponses = {
    /**
     * OK
     */
    200: ListString;
};

export type ConnectHostsResponse = ConnectHostsResponses[keyof ConnectHostsResponses];

export type CreateIndexCreateData = {
    body: CreateIndexCreateInBodyWritable;
    path?: never;
    query?: never;
    url: '/create_index/create';
};

export type CreateIndexCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateIndexCreateError = CreateIndexCreateErrors[keyof CreateIndexCreateErrors];

export type CreateIndexCreateResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type CreateIndexCreateResponse = CreateIndexCreateResponses[keyof CreateIndexCreateResponses];

export type CreateIndexGetMetadataData = {
    body: CreateIndexGetMetaInBodyWritable;
    path?: never;
    query?: never;
    url: '/create_index/get_index_metadata';
};

export type CreateIndexGetMetadataErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateIndexGetMetadataError = CreateIndexGetMetadataErrors[keyof CreateIndexGetMetadataErrors];

export type CreateIndexGetMetadataResponses = {
    /**
     * OK
     */
    200: Metadata;
};

export type CreateIndexGetMetadataResponse = CreateIndexGetMetadataResponses[keyof CreateIndexGetMetadataResponses];

export type DataExplorerSaveData = {
    body: DataExplorerSaveInBodyWritable;
    path?: never;
    query?: never;
    url: '/data_explorer/save';
};

export type DataExplorerSaveErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DataExplorerSaveError = DataExplorerSaveErrors[keyof DataExplorerSaveErrors];

export type DataExplorerSaveResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type DataExplorerSaveResponse = DataExplorerSaveResponses[keyof DataExplorerSaveResponses];

export type DataExplorerSearchData = {
    body: DataExplorerSearchInBodyWritable;
    path?: never;
    query?: never;
    url: '/data_explorer/search';
};

export type DataExplorerSearchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DataExplorerSearchError = DataExplorerSearchErrors[keyof DataExplorerSearchErrors];

export type DataExplorerSearchResponses = {
    /**
     * OK
     */
    200: DataExplorerResult;
};

export type DataExplorerSearchResponse = DataExplorerSearchResponses[keyof DataExplorerSearchResponses];

export type IndexSettingsGetData = {
    body: IndexSettingsGetInBodyWritable;
    path?: never;
    query?: never;
    url: '/index_settings';
};

export type IndexSettingsGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type IndexSettingsGetError = IndexSettingsGetErrors[keyof IndexSettingsGetErrors];

export type IndexSettingsGetResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type IndexSettingsGetResponse = IndexSettingsGetResponses[keyof IndexSettingsGetResponses];

export type IndexSettingsUpdateData = {
    body: IndexSettingsUpdateInBodyWritable;
    path?: never;
    query?: never;
    url: '/index_settings/update';
};

export type IndexSettingsUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type IndexSettingsUpdateError = IndexSettingsUpdateErrors[keyof IndexSettingsUpdateErrors];

export type IndexSettingsUpdateResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type IndexSettingsUpdateResponse = IndexSettingsUpdateResponses[keyof IndexSettingsUpdateResponses];

export type NavbarData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/navbar';
};

export type NavbarErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type NavbarError = NavbarErrors[keyof NavbarErrors];

export type NavbarResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type NavbarResponse = NavbarResponses[keyof NavbarResponses];

export type NodesData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/nodes';
};

export type NodesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type NodesError = NodesErrors[keyof NodesErrors];

export type NodesResponses = {
    /**
     * OK
     */
    200: ListNode;
};

export type NodesResponse = NodesResponses[keyof NodesResponses];

export type OverviewData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/overview';
};

export type OverviewErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewError = OverviewErrors[keyof OverviewErrors];

export type OverviewResponses = {
    /**
     * OK
     */
    200: Overview;
};

export type OverviewResponse = OverviewResponses[keyof OverviewResponses];

export type OverviewClearIndicesCacheData = {
    body: OverviewIndicesInBodyWritable;
    path?: never;
    query?: never;
    url: '/overview/clear_indices_cache';
};

export type OverviewClearIndicesCacheErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewClearIndicesCacheError = OverviewClearIndicesCacheErrors[keyof OverviewClearIndicesCacheErrors];

export type OverviewClearIndicesCacheResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewClearIndicesCacheResponse = OverviewClearIndicesCacheResponses[keyof OverviewClearIndicesCacheResponses];

export type OverviewCloseIndicesData = {
    body: OverviewIndicesInBodyWritable;
    path?: never;
    query?: never;
    url: '/overview/close_indices';
};

export type OverviewCloseIndicesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewCloseIndicesError = OverviewCloseIndicesErrors[keyof OverviewCloseIndicesErrors];

export type OverviewCloseIndicesResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewCloseIndicesResponse = OverviewCloseIndicesResponses[keyof OverviewCloseIndicesResponses];

export type OverviewDeleteIndicesData = {
    body: OverviewIndicesInBodyWritable;
    path?: never;
    query?: never;
    url: '/overview/delete_indices';
};

export type OverviewDeleteIndicesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewDeleteIndicesError = OverviewDeleteIndicesErrors[keyof OverviewDeleteIndicesErrors];

export type OverviewDeleteIndicesResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewDeleteIndicesResponse = OverviewDeleteIndicesResponses[keyof OverviewDeleteIndicesResponses];

export type OverviewDisableShardAllocationData = {
    body: OverviewShardKindInBodyWritable;
    path?: never;
    query?: never;
    url: '/overview/disable_shard_allocation';
};

export type OverviewDisableShardAllocationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewDisableShardAllocationError = OverviewDisableShardAllocationErrors[keyof OverviewDisableShardAllocationErrors];

export type OverviewDisableShardAllocationResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewDisableShardAllocationResponse = OverviewDisableShardAllocationResponses[keyof OverviewDisableShardAllocationResponses];

export type OverviewEnableShardAllocationData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/overview/enable_shard_allocation';
};

export type OverviewEnableShardAllocationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewEnableShardAllocationError = OverviewEnableShardAllocationErrors[keyof OverviewEnableShardAllocationErrors];

export type OverviewEnableShardAllocationResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewEnableShardAllocationResponse = OverviewEnableShardAllocationResponses[keyof OverviewEnableShardAllocationResponses];

export type OverviewFlushIndicesData = {
    body: OverviewIndicesInBodyWritable;
    path?: never;
    query?: never;
    url: '/overview/flush_indices';
};

export type OverviewFlushIndicesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewFlushIndicesError = OverviewFlushIndicesErrors[keyof OverviewFlushIndicesErrors];

export type OverviewFlushIndicesResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewFlushIndicesResponse = OverviewFlushIndicesResponses[keyof OverviewFlushIndicesResponses];

export type OverviewForceMergeData = {
    body: OverviewIndicesInBodyWritable;
    path?: never;
    query?: never;
    url: '/overview/force_merge';
};

export type OverviewForceMergeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewForceMergeError = OverviewForceMergeErrors[keyof OverviewForceMergeErrors];

export type OverviewForceMergeResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewForceMergeResponse = OverviewForceMergeResponses[keyof OverviewForceMergeResponses];

export type OverviewShardStatsData = {
    body: OverviewShardStatsInBodyWritable;
    path?: never;
    query?: never;
    url: '/overview/get_shard_stats';
};

export type OverviewShardStatsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewShardStatsError = OverviewShardStatsErrors[keyof OverviewShardStatsErrors];

export type OverviewShardStatsResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewShardStatsResponse = OverviewShardStatsResponses[keyof OverviewShardStatsResponses];

export type OverviewOpenIndicesData = {
    body: OverviewIndicesInBodyWritable;
    path?: never;
    query?: never;
    url: '/overview/open_indices';
};

export type OverviewOpenIndicesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewOpenIndicesError = OverviewOpenIndicesErrors[keyof OverviewOpenIndicesErrors];

export type OverviewOpenIndicesResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewOpenIndicesResponse = OverviewOpenIndicesResponses[keyof OverviewOpenIndicesResponses];

export type OverviewRefreshIndicesData = {
    body: OverviewIndicesInBodyWritable;
    path?: never;
    query?: never;
    url: '/overview/refresh_indices';
};

export type OverviewRefreshIndicesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewRefreshIndicesError = OverviewRefreshIndicesErrors[keyof OverviewRefreshIndicesErrors];

export type OverviewRefreshIndicesResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewRefreshIndicesResponse = OverviewRefreshIndicesResponses[keyof OverviewRefreshIndicesResponses];

export type OverviewRelocateShardData = {
    body: OverviewRelocateInBodyWritable;
    path?: never;
    query?: never;
    url: '/overview/relocate_shard';
};

export type OverviewRelocateShardErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OverviewRelocateShardError = OverviewRelocateShardErrors[keyof OverviewRelocateShardErrors];

export type OverviewRelocateShardResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type OverviewRelocateShardResponse = OverviewRelocateShardResponses[keyof OverviewRelocateShardResponses];

export type RepositoriesListData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/repositories';
};

export type RepositoriesListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RepositoriesListError = RepositoriesListErrors[keyof RepositoriesListErrors];

export type RepositoriesListResponses = {
    /**
     * OK
     */
    200: ListRepository;
};

export type RepositoriesListResponse = RepositoriesListResponses[keyof RepositoriesListResponses];

export type RepositoriesCreateData = {
    body: RepositoriesCreateInBodyWritable;
    path?: never;
    query?: never;
    url: '/repositories/create';
};

export type RepositoriesCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RepositoriesCreateError = RepositoriesCreateErrors[keyof RepositoriesCreateErrors];

export type RepositoriesCreateResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type RepositoriesCreateResponse = RepositoriesCreateResponses[keyof RepositoriesCreateResponses];

export type RepositoriesDeleteData = {
    body: RepositoriesDeleteInBodyWritable;
    path?: never;
    query?: never;
    url: '/repositories/delete';
};

export type RepositoriesDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RepositoriesDeleteError = RepositoriesDeleteErrors[keyof RepositoriesDeleteErrors];

export type RepositoriesDeleteResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type RepositoriesDeleteResponse = RepositoriesDeleteResponses[keyof RepositoriesDeleteResponses];

export type RestIndexData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/rest';
};

export type RestIndexErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RestIndexError = RestIndexErrors[keyof RestIndexErrors];

export type RestIndexResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type RestIndexResponse = RestIndexResponses[keyof RestIndexResponses];

export type RestHistoryData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/rest/history';
};

export type RestHistoryErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RestHistoryError = RestHistoryErrors[keyof RestHistoryErrors];

export type RestHistoryResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type RestHistoryResponse = RestHistoryResponses[keyof RestHistoryResponses];

export type RestRequestData = {
    body: RestRequestInBodyWritable;
    path?: never;
    query?: never;
    url: '/rest/request';
};

export type RestRequestErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RestRequestError = RestRequestErrors[keyof RestRequestErrors];

export type RestRequestResponses = {
    /**
     * OK
     */
    200: RestRequestResponse;
};

export type RestRequestResponse2 = RestRequestResponses[keyof RestRequestResponses];

export type SnapshotsGetData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/snapshots';
};

export type SnapshotsGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SnapshotsGetError = SnapshotsGetErrors[keyof SnapshotsGetErrors];

export type SnapshotsGetResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type SnapshotsGetResponse = SnapshotsGetResponses[keyof SnapshotsGetResponses];

export type SnapshotsCreateData = {
    body: SnapshotsCreateInBodyWritable;
    path?: never;
    query?: never;
    url: '/snapshots/create';
};

export type SnapshotsCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SnapshotsCreateError = SnapshotsCreateErrors[keyof SnapshotsCreateErrors];

export type SnapshotsCreateResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type SnapshotsCreateResponse = SnapshotsCreateResponses[keyof SnapshotsCreateResponses];

export type SnapshotsDeleteData = {
    body: SnapshotsDeleteInBodyWritable;
    path?: never;
    query?: never;
    url: '/snapshots/delete';
};

export type SnapshotsDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SnapshotsDeleteError = SnapshotsDeleteErrors[keyof SnapshotsDeleteErrors];

export type SnapshotsDeleteResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type SnapshotsDeleteResponse = SnapshotsDeleteResponses[keyof SnapshotsDeleteResponses];

export type SnapshotsLoadData = {
    body: SnapshotsLoadInBodyWritable;
    path?: never;
    query?: never;
    url: '/snapshots/load';
};

export type SnapshotsLoadErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SnapshotsLoadError = SnapshotsLoadErrors[keyof SnapshotsLoadErrors];

export type SnapshotsLoadResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type SnapshotsLoadResponse = SnapshotsLoadResponses[keyof SnapshotsLoadResponses];

export type SnapshotsRestoreData = {
    body: SnapshotsRestoreInBodyWritable;
    path?: never;
    query?: never;
    url: '/snapshots/restore';
};

export type SnapshotsRestoreErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SnapshotsRestoreError = SnapshotsRestoreErrors[keyof SnapshotsRestoreErrors];

export type SnapshotsRestoreResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type SnapshotsRestoreResponse = SnapshotsRestoreResponses[keyof SnapshotsRestoreResponses];

export type TemplatesListData = {
    body: HostBodyWritable;
    path?: never;
    query?: never;
    url: '/templates';
};

export type TemplatesListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TemplatesListError = TemplatesListErrors[keyof TemplatesListErrors];

export type TemplatesListResponses = {
    /**
     * OK
     */
    200: ListTemplate;
};

export type TemplatesListResponse = TemplatesListResponses[keyof TemplatesListResponses];

export type TemplatesCreateData = {
    body: TemplatesCreateInBodyWritable;
    path?: never;
    query?: never;
    url: '/templates/create';
};

export type TemplatesCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TemplatesCreateError = TemplatesCreateErrors[keyof TemplatesCreateErrors];

export type TemplatesCreateResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type TemplatesCreateResponse = TemplatesCreateResponses[keyof TemplatesCreateResponses];

export type TemplatesDeleteData = {
    body: TemplatesDeleteInBodyWritable;
    path?: never;
    query?: never;
    url: '/templates/delete';
};

export type TemplatesDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TemplatesDeleteError = TemplatesDeleteErrors[keyof TemplatesDeleteErrors];

export type TemplatesDeleteResponses = {
    /**
     * OK
     */
    200: RawResponse;
};

export type TemplatesDeleteResponse = TemplatesDeleteResponses[keyof TemplatesDeleteResponses];
