services:
  cerebro:
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      APPLICATION_SECRET: "example-secret-change-me"
      BASIC_AUTH_USER: "admin"
      BASIC_AUTH_PWD: "admin"
    volumes:
      - ./application.yaml:/opt/cerebro/conf/application.yaml:ro
    ports:
      - "9000:9000"
