services:
  cerebro:
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      APPLICATION_SECRET: "example-secret-change-me"
    volumes:
      - ./application.yaml:/opt/cerebro/conf/application.yaml:ro
    ports:
      - "9000:9000"
    depends_on:
      - open_ldap
  open_ldap:
    image: osixia/openldap:1.4.0
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./users:/opt
